#FosUserBundle Routes
fos_user_security_login:
    path: /login.html
    defaults:  { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults:  { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: /logout.html
    defaults:  { _controller: FOSUserBundle:Security:logout }

fos_user_registration_register:
    path: /register.html
    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_registration_check_email:
    path: /register/check-email.html
    defaults:  { _controller: FOSUserBundle:Registration:checkEmail }
    requirements: { _method: GET }

fos_user_registration_confirm:
    path: /register/confirm/{token}
    defaults:  { _controller: FOSUserBundle:Registration:confirm }
    requirements: { _method: GET }

fos_user_registration_confirmed:
    path: /register/confirmed.html
    defaults:  { _controller: FOSUserBundle:Registration:confirmed }
    requirements: { _method: GET }

fos_user_resetting_request:
    path: /reset-password.html
    defaults:  { _controller: FOSUserBundle:Resetting:request }
    requirements: { _method: GET }

fos_user_resetting_send_email:
    path: /reset-password/send-email.html
    defaults:  { _controller: FOSUserBundle:Resetting:sendEmail }
    requirements: { _method: POST }

fos_user_resetting_check_email:
    path: /reset-password/check-email.html
    defaults:  { _controller: FOSUserBundle:Resetting:checkEmail }
    requirements: { _method: GET }

fos_user_resetting_reset:
    path: /reset-password/reset/{token}
    defaults:  { _controller: FOSUserBundle:Resetting:reset }
    requirements: { _method: GET|POST }

fos_user_change_password:
    path: /profile/change-password.html
    defaults:  { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements: { _method: GET|POST }

fos_user_profile_show:
    path: /profile
    defaults:  { _controller: FOSUserBundle:Profile:show }
    requirements: { _method: GET }

fos_user_profile_edit:
    path: /profile/edit.html
    defaults:  { _controller: FOSUserBundle:Profile:edit }