# config/routes/dev/web_profiler.yaml

web_profiler_wdt:
    resource: "../../../vendor/symfony/web-profiler-bundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

web_profiler_router:
    resource: "../../../vendor/symfony/web-profiler-bundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler