imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_domain: "%project_domain%"
    fragments:       ~
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        -  'bootstrap_3_layout.html.twig'
    globals:
        project: "%project%"
        login_form: true
        is_damis_algorithm_enabled: "%is_damis_algorithm_enabled%"
        design_style: "%design_style%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ DamisExperimentBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        mapping_types:
          enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Commented during upgrade to Symfony 3.4
# stof_doctrine_extensions:
#         default_locale: en_us
#         translation_fallback: true
#         uploadable:
#             validate_writable_directory: false
#         orm:
#             default:
#                 timestampable: true
#                 sluggable: true
#                 tree: true
#                 loggable: true

# fos_user:
#     db_driver: orm
#     firewall_name: main
#     user_class: Base\UserBundle\Entity\User
#     from_email:
#         address:        "%project_email%"
#         sender_name:    "%project%"
#     change_password:
#         form:
#             type: base_user_change_password
#     profile:
#         form:
#             type: base_user_profile
#     resetting:
#         email:
#             from_email:
#                 address:        "%project_email%"
#                 sender_name:    "%project%"
#         form:
#             type: base_user_resetting
#     registration:
#         form:
#             type: base_user_registration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Base\UserBundle\Entity\User
    from_email:
        address:        "%project_email%"
        sender_name:    "%project%"
    change_password:
        form:
            type: Base\UserBundle\Form\Type\ChangePasswordFormType
    profile:
        form:
            type: Base\UserBundle\Form\Type\ProfileFormType
    resetting:
        email:
            from_email:
                address:        "%project_email%"
                sender_name:    "%project%"
        form:
            type: Base\UserBundle\Form\Type\ResettingFormType
    registration:
        form:
            type: Base\UserBundle\Form\Type\RegistrationFormType

# Commented during upgrade to Symfony 3.4
# apy_data_grid:
#     pagerfanta:
#         enable: true    #default false
#         view_class: Pagerfanta\View\DefaultView #default    Pagerfanta\View\DefaultView
#         options:            #all options of pager fanta view constructor
#            previous_message : «
#            next_message : »
#            proximity: 3

apy_data_grid:
    persistence: true
    no_data_message: No data
    no_result_message: No result

# Commented during upgrade to Symfony 3.4
iphp_file_store:
    mappings:
        dataset: 
            upload_dir: '%kernel.project_dir%/web/uploads/datasets'
            upload_path: '/uploads/datasets'
            namer:
                translit: ~
                property:
                    params: { field : datasetIdMd5 }
            directory_namer:
                property:
                    params: { field: userIdMd5Dataset }
            delete_on_remove: true
            overwrite_duplicates: true
            
        algorithmfile:
            upload_dir: '%kernel.project_dir%/web/uploads/algorithms'
            upload_path: '/uploads/algorithms'
            namer:
                translit: ~
                property:
                    params: { field : fileIdMd5 }
            directory_namer:
                property:
                    params: { field: userIdMd5File }
            delete_on_remove: true
            overwrite_duplicates: true

knp_paginator:
    page_range: 13
    default_options:
        page_name: page
    template:
        pagination: BaseStaticBundle:General:paginator.html.twig
