imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @BCCCronManagerBundle/Resources/config/assetic.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        cookie_domain: "%project_domain%"
        # handler_id set to null will use default session handler from php.ini
        # if commented, sessions will be storred in cache folders
        #handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ DamisExperimentBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        mapping_types:
          enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stof_doctrine_extensions:
        default_locale: en_us
        translation_fallback: true
        uploadable:
            validate_writable_directory: false
        orm:
            default:
                timestampable: true
                sluggable: true
                tree: true
                loggable: true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Base\UserBundle\Entity\User
    change_password:
        form:
            type: base_user_change_password
    profile:
        form:
            type: base_user_profile
    resetting:
        email:
            from_email:
                address:        "%project_email%"
                sender_name:    "%project%"
        form:
            type: base_user_resetting
    registration:
        form:
            type: base_user_registration

twig:
    globals:
        project: "%project%"
        login_form: true

apy_data_grid:
    pagerfanta:
        enable: true    #default false
        view_class: Pagerfanta\View\DefaultView #default    Pagerfanta\View\DefaultView
        options:            #all options of pager fanta view constructor
           previous_message : «
           next_message : »
           proximity: 3

iphp_file_store:
    mappings:
        dataset:
            upload_dir:  %kernel.root_dir%/../web/assets
            upload_path: /assets
            namer:
                translit: ~
                property:
                    params: { field : datasetIdMd5 }
            directory_namer:
                property:
                    params: { field: userIdMd5Dataset }
            delete_on_remove: true
            overwrite_duplicates: true

knp_paginator:
    page_range: 13
    default_options:
        page_name: page
    template:
        pagination: BaseStaticBundle:General:paginator.html.twig