# fos_user_registration_register:
#     path:      /register.html
#     defaults:  { _controller: fos_user.controller.registration:registerAction }

damis_algorithm:
    resource: "@DamisAlgorithmBundle/Controller/"
    type:     annotation
    prefix:   /

damis_datasets:
    resource: "@DamisDatasetsBundle/Controller/"
    type:     annotation
    prefix:   /

damis_experiment:
    resource: "@DamisExperimentBundle/Controller/"
    type:     annotation
    prefix:   /

base_static:
    resource: "@BaseStaticBundle/Controller/"
    type:     annotation
    prefix:   /

base_user:
    resource: "@BaseUserBundle/Controller/"
    type:     annotation
    prefix:   /

base_main:
    resource: "@BaseMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# BCCCronManagerBundle was removed - now using custom Cron Manager in BaseMainBundle
# BCCCronManagerBundle:
#     resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
#     prefix:   /cron

# base_user_fos:
#     resource: "@BaseUserBundle/Resources/config/routing.yml"
#     prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# This handles /register/*
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register 

# This handles /resetting/*
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset-password 

# This handles /profile/*
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# This handles /profile/change-password
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

base_convert:
    resource: "@BaseConvertBundle/Controller/"
    type:     annotation
    prefix:   /

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"