damis_datasets:
    resource: "@DamisDatasetsBundle/Controller/"
    type:     annotation
    prefix:   /

damis_experiment:
    resource: "@DamisExperimentBundle/Controller/"
    type:     annotation
    prefix:   /

base_user:
    resource: "@BaseUserBundle/Controller/"
    type:     annotation
    prefix:   /

base_main:
    resource: "@BaseMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

BCCCronManagerBundle:
    resource: "@BCCCronManagerBundle/Resources/config/routing.xml"
    prefix:   /cron

base_user_fos:
    resource: "@BaseUserBundle/Resources/config/routing.yml"
    prefix: /

base_convert:
    resource: "@BaseConvertBundle/Controller/"
    type:     annotation
    prefix:   /